# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c25b4e132cb79169d3623c24a804beef57b9dfc8faf59fa2895e242b8083d366d068daa29392ad9b6cab9c280d3b96010874150ff440a03d4546e9bdb4b92ccb

test:
  secret_key_base: 9acd571e66644db95fc51a02268fd0b83632fab9eea0b3b8df47c4f32dcbaae3265dd4840460f03a4c568cef0855f7458a32bf0913906d5f8b8243bd2c47c4b0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
